<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P3B-6CW7NK2" ignored="1" name="Test1" tests="21" failures="6" timestamp="2019-12-10T16:38:07 IST" time="82.688" errors="0">
  <testcase name="Test1" time="0.01" classname="testngFeatures.DemoAssertions"/>
  <testcase name="Test2" time="0.002" classname="testngFeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="Error Msg- 20 is greater than 18 did not expect to find [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Error Msg- 20 is greater than 18 did not expect to find [false] but found [true]
at testngFeatures.DemoAssertions.Test2(DemoAssertions.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="testngFeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at testngFeatures.DemoAssertions.Test3(DemoAssertions.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="0.001" classname="testngFeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="expected [Sele] but found [Selenium]">
      <![CDATA[java.lang.AssertionError: expected [Sele] but found [Selenium]
at testngFeatures.DemoAssertions.Test4(DemoAssertions.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test5" time="0.004" classname="testngFeatures.DemoAssertions"/>
  <testcase name="Test6" time="0.004" classname="testngFeatures.DemoAssertions"/>
  <testcase name="Test7" time="0.002" classname="testngFeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testngFeatures.DemoAssertions.Test7(DemoAssertions.java:53)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Test7 -->
  <testcase name="Test8" time="0.002" classname="testngFeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="I wanted it to fails son">
      <![CDATA[java.lang.AssertionError: I wanted it to fails son
at testngFeatures.DemoAssertions.Test8(DemoAssertions.java:60)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test8 -->
  <testcase name="f" time="0.009" classname="testngFeatures.DemoSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Hi] but found [Hello],
	Erroe Msg - Both values are same did not expect to find [10] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hi] but found [Hello],
Erroe Msg - Both values are same did not expect to find [10] but found [10]
at testngFeatures.DemoSoftAssert.f(DemoSoftAssert.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.001" classname="testngFeatures.ExecutionSeq"/>
  <testcase name="f" time="69.367" classname="testngFeatures.LoginMercury"/>
  <testcase name="f" time="0.001" classname="testngFeatures.NewTestDemo"/>
  <testcase name="login" time="0.001" classname="testngFeatures.DemoDataProvider"/>
  <testcase name="login" time="0.001" classname="testngFeatures.DemoDataProvider"/>
  <testcase name="login" time="0.001" classname="testngFeatures.DemoDataProvider"/>
  <testcase name="openBrowser" time="0.001" classname="testngFeatures.MercuryAPP"/>
  <testcase name="openURL" time="0.001" classname="testngFeatures.MercuryAPP"/>
  <testcase name="Login" time="0.001" classname="testngFeatures.MercuryAPP"/>
  <testcase name="bookFlight" time="0.002" classname="testngFeatures.MercuryAPP"/>
  <testcase name="logout" time="0.001" classname="testngFeatures.MercuryAPP"/>
  <testcase name="closeBrowser" time="0.001" classname="testngFeatures.MercuryAPP"/>
  <testcase name="searchFlight" time="0.0" classname="testngFeatures.MercuryAPP">
    <ignored/>
  </testcase> <!-- searchFlight -->
</testsuite> <!-- Test1 -->
